[package]
name = "yellowstone-vixen-yellowstone-fumarole-source"
version = "0.3.1"
edition.workspace = true
description = "Yellowstone Fumarole source for the Yellowstone Vixen"
repository.workspace = true
authors.workspace = true
license.workspace = true

readme = "./../../README.md"

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing = { workspace = true }
futures-util = { workspace = true, features = ["sink"] }
yellowstone-vixen = { workspace = true }
yellowstone-vixen-core = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
yellowstone-fumarole-client = { workspace = true, features = [
  "prometheus",
] }
bytesize = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tonic = { workspace = true, features = ["gzip", "zstd"] }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
prometheus = { workspace = true }

[features]
prometheus = []
