[package]
name = "yellowstone-vixen-yellowstone-grpc-source"
version = "0.3.1"
edition.workspace = true
description = "Yellowstone gRPC source for the Yellowstone Vixen"
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "./README.md"

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing = { workspace = true }
futures-util = { workspace = true, features = ["sink"] }
yellowstone-vixen = { workspace = true }
yellowstone-vixen-core = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
yellowstone-grpc-client = { workspace = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
